package com.samplespace.service_add_upgrade;

import com.samplespace.service_add_upgrade.customer;
import com.samplespace.service_add_upgrade.service;
import com.samplespace.service_add_upgrade.serviceRequest;

import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.temporal.ChronoUnit;
import java.time.LocalDate;

function boolean chkContractEndDate(String contractEndDate) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date passedDate = dateFormat.parse(contractEndDate);
    return passedDate.after(new Date());
}

function int getBalance(int monthlyPay, String contractEndDate) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String currDate = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
    Date passedDate = dateFormat.parse(contractEndDate);
    return (int) (Math.ceil((double) ChronoUnit.DAYS.between(LocalDate.parse(currDate), LocalDate.parse(contractEndDate))/30) * monthlyPay);

}

rule "chkBalCont"

	when
		c1: customer(customer.service.endDate != "")
	then
	    System.out.println("In Chk Contract");
        //sr = new serviceRequest();
        //sr.setContractActive(true);
        //c1.setName("True");
        System.out.println("In Chk Contract");
    end


    