package com.samplespace.device_upgrade;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer Id")
	private java.lang.String customerId;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Date of Birth")
	private java.util.Date dob;
	@org.kie.api.definition.type.Label("Phone")
	private java.lang.String phone;
	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label("Address")
	private java.util.List<com.samplespace.device_upgrade.address> address;

	@org.kie.api.definition.type.Label("Customer Rule Check Result")
	private com.samplespace.device_upgrade.custRuleChkRes ruleCheck;

	@org.kie.api.definition.type.Label("Credit Score")
	private java.lang.Integer creditScore;

	@org.kie.api.definition.type.Label("Contract")
	private contract contract;

	public customer() {
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.Date getDob() {
		return this.dob;
	}

	public void setDob(java.util.Date dob) {
		this.dob = dob;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.util.List<com.samplespace.device_upgrade.address> getAddress() {
		return this.address;
	}

	public void setAddress(
			java.util.List<com.samplespace.device_upgrade.address> address) {
		this.address = address;
	}

	public com.samplespace.device_upgrade.custRuleChkRes getRuleCheck() {
		return this.ruleCheck;
	}

	public void setRuleCheck(
			com.samplespace.device_upgrade.custRuleChkRes ruleCheck) {
		this.ruleCheck = ruleCheck;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public com.samplespace.device_upgrade.contract getContract() {
		return this.contract;
	}

	public void setContract(com.samplespace.device_upgrade.contract contract) {
		this.contract = contract;
	}

	public customer(java.lang.String customerId, java.lang.String name,
			java.util.Date dob, java.lang.String phone, java.lang.String email,
			java.util.List<com.samplespace.device_upgrade.address> address,
			com.samplespace.device_upgrade.custRuleChkRes ruleCheck,
			java.lang.Integer creditScore,
			com.samplespace.device_upgrade.contract contract) {
		this.customerId = customerId;
		this.name = name;
		this.dob = dob;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.ruleCheck = ruleCheck;
		this.creditScore = creditScore;
		this.contract = contract;
	}

}