package com.samplespace.service_add_upgrade;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ServiceRequest() {
    }




}