package com.samplespace.service_add_upgrade;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class service implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Product Id")
	private java.lang.String productId;
	@org.kie.api.definition.type.Label("Product Name")
	private java.lang.String productName;

	@org.kie.api.definition.type.Label("Product Description")
	private java.lang.String productDescription;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("Start Date")
	private String startDate;

	@org.kie.api.definition.type.Label("End Date")
	private String endDate;

	public service() {
	}

	public java.lang.String getProductId() {
		return this.productId;
	}

	public void setProductId(java.lang.String productId) {
		this.productId = productId;
	}

	public java.lang.String getProductName() {
		return this.productName;
	}

	public void setProductName(java.lang.String productName) {
		this.productName = productName;
	}

	public java.lang.String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(java.lang.String productDescription) {
		this.productDescription = productDescription;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.lang.String startDate) {
		this.startDate = startDate;
	}

	public java.lang.String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.lang.String endDate) {
		this.endDate = endDate;
	}

	public service(java.lang.String productId, java.lang.String productName,
			java.lang.String productDescription, java.lang.String type,
			java.lang.String startDate, java.lang.String endDate) {
		this.productId = productId;
		this.productName = productName;
		this.productDescription = productDescription;
		this.type = type;
		this.startDate = startDate;
		this.endDate = endDate;
	}

}